version: '2.4'

services:
  web_app:
    image: esse/web_app
    ports:
      - "9292:9292"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE=/app/data/database.jsonl
  parser:
    image: esse/parser
    command: ruby run.rb
    environment:
      - DATABASE=/app/data/database.jsonl
    volumes:
      - ./data:/app/data
