version: '2.4'

services:
  web_app:
    image: esse/dahlia-web_app
    ports:
      - "9292:9292"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE=/app/data/database.jsonl
  parser:
    image: esse/dahlia-parser
    command: bundle exec ruby cli.rb -w /app/data/database.jsonl
    volumes:
      - ./data:/app/data
