url: "http://berghain.de/events/"
list:
  - operand: xpath
    argument: "//div[@class='content']/div[@class='x3cols']/div[contains(@class, 'col_teaser')]"
pagination:
  - operand: xpath
    argument: ""
attributes:
  name:
    - operand: xpath
      argument: ".//h4/span/a/span"
    - operand: inner_html # TODO - maybe this can be included in the xpath?
  description:
    - operand: constant
      argument: "TODO"
  date_from:
    - operand: constant
      argument: "TODO"
  date_to:
    - operand: constant
      argument: "TODO"
  source:
    - operand: constant
      argument: "berghain"
