url: "http://berghain.de/events/"
list:
  - operand: xpath
    argument: "//div[@class='content']/div[@class='x3cols']/div[contains(@class, 'col_teaser')]"
attributes:
  name:
    - operand: xpath
      argument: ".//h4/span/a/span"
    - operand: inner_html # TODO - maybe this can be included in the xpath?
  description:
    - operand: constant
      argument: "TODO"
  date_from:
    - operand: xpath
      argument: ".//h4/span/a"
    - operand: inner_html
    - operand: first_match_group_from_regexp
      argument: ^\s+([A-Za-z0-9 ]+)\s+\<span
  date_to:
    - operand: xpath
      argument: ".//h4/span/a"
    - operand: inner_html
    - operand: first_match_group_from_regexp
      argument: ^\s+([A-Za-z0-9 ]+)\s+\<span
  source:
    - operand: constant
      argument: "berghain"
