url: "http://berghain.de/events/"
list:
  - operand: xpath
    argument: "//div[@class='content']/div[@class='x3cols']/div[contains(@class, 'col_teaser')]"
attributes:
  name:
    - operand: xpath
      argument: ".//h4/span/a/span"
    - operand: inner_html
  link:
    - operand: xpath
      argument: ".//h4/span/a"
    - operand: attr
      argument: href
    - operand: prepend_single_string
      argument: "http://berghain.de"
  date_from:
    - operand: xpath
      argument: ".//h4/span/a"
    - operand: inner_html
    - operand: first_match_group_from_regexp
      argument: ^\s+([A-Za-z0-9 ]+)\s+\<span
    - operand: parse_as_date
  date_to:
    - operand: xpath
      argument: ".//h4/span/a"
    - operand: inner_html
    - operand: first_match_group_from_regexp
      argument: ^\s+([A-Za-z0-9 ]+)\s+\<span
    - operand: parse_as_date
  source:
    - operand: constant
      argument: "berghain"
