url: "https://www.co-berlin.org/en/calender"
list:
  - operand: xpath
    argument: "//div[@class='view-content']/div[@class='seite-c-single']"
pagination:
  - operand: concat
    argument:
    - - operand: xpath
        argument: "//div[@class='pagination-centered']/div[@class='item-list']/ul/li/a"
      - operand: extract_href
      - operand: compact
      - operand: prepend_string
        argument: "https://www.co-berlin.org"
    - - operand: xpath
        argument: "//link[@rel='canonical']"
      - operand: extract_href
  - operand: uniq
attributes:
  name:
    - operand: xpath
      argument: ".//div[@class='article-title']"
    - operand: inner_html
  description:
    - operand: constant
      argument: "TODO"
  date_from:
    - operand: or
      argument:
      - - operand: xpath
          argument: ".//div[@class='article-over-title']/span[@class='article-date']/div[@class='date-display-range']/span[@class='date-display-start']"
        - operand: attr
          argument: content
      - - operand: xpath
          argument: ".//div[@class='article-over-title']/span[@class='article-date']/span[@class='date-display-single']"
    - operand: parse_as_date
  date_to:
    - operand: or
      argument:
      - - operand: xpath
          argument: ".//div[@class='article-over-title']/span[@class='article-date']/div[@class='date-display-range']/span[@class='date-display-end']"
        - operand: attr
          argument: content
      - - operand: xpath
          argument: ".//div[@class='article-over-title']/span[@class='article-date']/span[@class='date-display-single']"
    - operand: parse_as_date
  source:
    - operand: constant
      argument: "co-berlin"
