url: "https://www.co-berlin.org/en/calender"
list:
  - operand: xpath
    argument: "//div[@class='view-content']/div[@class='seite-c-single']"
pagination:
  - operand: xpath
    argument: ""
attributes:
  name:
    - operand: xpath
      argument: ".//div[@class='article-title']"
    - operand: inner_html
  description:
    - operand: constant
      argument: "TODO"
  date_from:
    - operand: xpath
      argument: ".//div[@class='article-over-title']/span[@class='article-date']/div[@class='date-display-range']/span[@class='date-display-start']"
    - operand: attr
      argument: content
    # - operand: parse_as_date
  date_to:
    - operand: xpath
      argument: ".//div[@class='article-over-title']/span[@class='article-date']/div[@class='date-display-range']/span[@class='date-display-end']"
    - operand: attr
      argument: content
    # - operand: parse_as_date
  source:
    - operand: constant
      argument: "co-berlin"
