url: "https://www.co-berlin.org/en/calender"
list:
  - operand: xpath
    argument: "//div[@class='view-content']/div[@class='seite-c-single']"
pagination:
  - operand: xpath
    argument: ""
attributes:
  name:
    - operand: xpath
      argument: ".//div[@class='article-title']"
    - operand: inner_html
  description:
    - operand: constant
      argument: "TODO"
  date_from:
    - operand: constant
      argument: "TODO"
  date_to:
    - operand: constant
      argument: "TODO"
  hour_from:
    - operand: constant
      argument: "TODO"
  hour_to:
    - operand: constant
      argument: "TODO"
  source:
    - operand: constant
      argument: "co-berlin"
