# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.2'

gem 'jsonl'
gem 'puma'
gem 'sinatra'

group :development do
  gem 'rubocop', require: false
  gem 'pry'
end

group :test do
  gem 'rspec'
  gem 'simplecov', require: false
end
