# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.2'

gem 'httparty'
gem 'nokogiri'

group :development do
  gem 'rubocop', require: false
end

group :test do
  gem 'rspec'
end

